(cl:in-package erc_aruco_msg-srv)
(cl:export '(TAG1-VAL
          TAG1
          TAG2-VAL
          TAG2
          TAG3-VAL
          TAG3
          TAG4-VAL
          TAG4
          TAG5-VAL
          TAG5
          TAG6-VAL
          TAG6
          TAG7-VAL
          TAG7
          TAG8-VAL
          TAG8
          TAG9-VAL
          TAG9
          TAG10-VAL
          TAG10
          TAG11-VAL
          TAG11
          TAG12-VAL
          TAG12
          TAG13-VAL
          TAG13
          TAG14-VAL
          TAG14
          SCORE-VAL
          SCORE
))