// Generated by gencpp from file erc_aruco_msg/ErcAruco.msg
// DO NOT EDIT!


#ifndef ERC_ARUCO_MSG_MESSAGE_ERCARUCO_H
#define ERC_ARUCO_MSG_MESSAGE_ERCARUCO_H

#include <ros/service_traits.h>


#include <erc_aruco_msg/ErcArucoRequest.h>
#include <erc_aruco_msg/ErcArucoResponse.h>


namespace erc_aruco_msg
{

struct ErcAruco
{

typedef ErcArucoRequest Request;
typedef ErcArucoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ErcAruco
} // namespace erc_aruco_msg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::erc_aruco_msg::ErcAruco > {
  static const char* value()
  {
    return "715a825b614df3219624e3f0adb1b4b3";
  }

  static const char* value(const ::erc_aruco_msg::ErcAruco&) { return value(); }
};

template<>
struct DataType< ::erc_aruco_msg::ErcAruco > {
  static const char* value()
  {
    return "erc_aruco_msg/ErcAruco";
  }

  static const char* value(const ::erc_aruco_msg::ErcAruco&) { return value(); }
};


// service_traits::MD5Sum< ::erc_aruco_msg::ErcArucoRequest> should match
// service_traits::MD5Sum< ::erc_aruco_msg::ErcAruco >
template<>
struct MD5Sum< ::erc_aruco_msg::ErcArucoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::erc_aruco_msg::ErcAruco >::value();
  }
  static const char* value(const ::erc_aruco_msg::ErcArucoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::erc_aruco_msg::ErcArucoRequest> should match
// service_traits::DataType< ::erc_aruco_msg::ErcAruco >
template<>
struct DataType< ::erc_aruco_msg::ErcArucoRequest>
{
  static const char* value()
  {
    return DataType< ::erc_aruco_msg::ErcAruco >::value();
  }
  static const char* value(const ::erc_aruco_msg::ErcArucoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::erc_aruco_msg::ErcArucoResponse> should match
// service_traits::MD5Sum< ::erc_aruco_msg::ErcAruco >
template<>
struct MD5Sum< ::erc_aruco_msg::ErcArucoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::erc_aruco_msg::ErcAruco >::value();
  }
  static const char* value(const ::erc_aruco_msg::ErcArucoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::erc_aruco_msg::ErcArucoResponse> should match
// service_traits::DataType< ::erc_aruco_msg::ErcAruco >
template<>
struct DataType< ::erc_aruco_msg::ErcArucoResponse>
{
  static const char* value()
  {
    return DataType< ::erc_aruco_msg::ErcAruco >::value();
  }
  static const char* value(const ::erc_aruco_msg::ErcArucoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ERC_ARUCO_MSG_MESSAGE_ERCARUCO_H
