// Generated by gencpp from file erc_aruco_msg/ErcArucoResponse.msg
// DO NOT EDIT!


#ifndef ERC_ARUCO_MSG_MESSAGE_ERCARUCORESPONSE_H
#define ERC_ARUCO_MSG_MESSAGE_ERCARUCORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace erc_aruco_msg
{
template <class ContainerAllocator>
struct ErcArucoResponse_
{
  typedef ErcArucoResponse_<ContainerAllocator> Type;

  ErcArucoResponse_()
    : score(0.0)  {
    }
  ErcArucoResponse_(const ContainerAllocator& _alloc)
    : score(0.0)  {
  (void)_alloc;
    }



   typedef float _score_type;
  _score_type score;





  typedef boost::shared_ptr< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ErcArucoResponse_

typedef ::erc_aruco_msg::ErcArucoResponse_<std::allocator<void> > ErcArucoResponse;

typedef boost::shared_ptr< ::erc_aruco_msg::ErcArucoResponse > ErcArucoResponsePtr;
typedef boost::shared_ptr< ::erc_aruco_msg::ErcArucoResponse const> ErcArucoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator1> & lhs, const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.score == rhs.score;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator1> & lhs, const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace erc_aruco_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "44f46b92fb243edcf5d498fd500e3a88";
  }

  static const char* value(const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x44f46b92fb243edcULL;
  static const uint64_t static_value2 = 0xf5d498fd500e3a88ULL;
};

template<class ContainerAllocator>
struct DataType< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "erc_aruco_msg/ErcArucoResponse";
  }

  static const char* value(const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 score\n"
"\n"
;
  }

  static const char* value(const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.score);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ErcArucoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::erc_aruco_msg::ErcArucoResponse_<ContainerAllocator>& v)
  {
    s << indent << "score: ";
    Printer<float>::stream(s, indent + "  ", v.score);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERC_ARUCO_MSG_MESSAGE_ERCARUCORESPONSE_H
